import os
import json
import urllib.request
import urllib.error

def run_ai_review(code_text, file_name, api_key=None):
    """
    Review code using Google Gemini model and return structured review JSON.
    Uses standard library urllib.request for maximum reliability.
    """
    if not api_key:
        api_key = os.environ.get("GEMINI_API_KEY")
        
    if not api_key:
        return {
            "enabled": False,
            "message": "AI analysis skipped. Please configure your API key in Settings to activate AI Code Review."
        }

    # Prompt instructing Gemini to audit the code and respond in structured JSON
    system_instruction = (
        "You are an expert Senior Software Engineer. You conduct deep code reviews. "
        "Your task is to analyze the user's uploaded code and provide feedback in JSON format. "
        "Your JSON response must match the following schema exactly:\n"
        "{\n"
        "  \"score\": 85,\n"
        "  \"summary\": \"Overall summary of the code quality and areas for improvement...\",\n"
        "  \"findings\": [\n"
        "    {\n"
        "      \"severity\": \"HIGH\" | \"MEDIUM\" | \"LOW\" | \"INFO\",\n"
        "      \"issue\": \"Short issue title\",\n"
        "      \"explanation\": \"Detailed explanation of why it is an issue\",\n"
        "      \"suggestion\": \"Concrete refactoring or code replacement suggestion\",\n"
        "      \"file_name\": \"filename.py\",\n"
        "      \"line_number\": 12\n"
        "    }\n"
        "  ],\n"
        "  \"bugs\": [\"Bug description 1\", \"Bug description 2\"],\n"
        "  \"optimizations\": [\"Performance tip 1\", \"Performance tip 2\"],\n"
        "  \"refactoring\": [\"Clean code tip 1\", \"Clean code tip 2\"],\n"
        "  \"documentation\": {\n"
        "    \"module\": \"Module level docstring explanation...\",\n"
        "    \"classes\": [\n"
        "      {\n"
        "        \"name\": \"ClassName\",\n"
        "        \"docstring\": \"Class docstring explanation...\"\n"
        "      }\n"
        "    ],\n"
        "    \"functions\": [\n"
        "      {\n"
        "        \"name\": \"function_name\",\n"
        "        \"docstring\": \"Function docstring explanation...\"\n"
        "      }\n"
        "    ]\n"
        "  }\n"
        "}\n"
        "Do not include any markdown backticks, explanations, or extra characters outside the JSON. Return only raw JSON."
    )

    prompt = f"File name: {file_name}\n\nCode content:\n```\n{code_text}\n```"

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={api_key}"
    
    # Request body structure for Gemini API
    req_body = {
        "contents": [
            {
                "parts": [
                    {"text": f"{system_instruction}\n\nReview the following code:\n{prompt}"}
                ]
            }
        ],
        "generationConfig": {
            "responseMimeType": "application/json"
        }
    }

    try:
        req_data = json.dumps(req_body).encode("utf-8")
        req = urllib.request.Request(
            url,
            data=req_data,
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        
        with urllib.request.urlopen(req, timeout=30) as response:
            res_data = response.read().decode("utf-8")
            res_json = json.loads(res_data)
            
            # Extract content from response structure
            candidates = res_json.get("candidates", [])
            if not candidates:
                return {"enabled": True, "error": "Gemini API returned no candidates."}
                
            parts = candidates[0].get("content", {}).get("parts", [])
            if not parts:
                return {"enabled": True, "error": "Gemini API returned empty parts."}
                
            raw_text = parts[0].get("text", "").strip()
            
            # Parse the inner JSON generated by the model
            parsed_review = json.loads(raw_text)
            parsed_review["enabled"] = True
            return parsed_review
            
    except urllib.error.HTTPError as http_err:
        try:
            err_body = http_err.read().decode("utf-8")
            err_json = json.loads(err_body)
            msg = err_json.get("error", {}).get("message", str(http_err))
        except Exception:
            msg = str(http_err)
        return {"enabled": True, "error": f"Gemini API Error: {msg}"}
        
    except Exception as e:
        return {"enabled": True, "error": f"General Error: {str(e)}"}
